apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-ns
spec:
  type: NodePort
  selector:
    app: webapp      
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000