apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 826055043381.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
